#配置公共信息
#冒号左边全小写
server:
  port: 8080
  
logging:
  level:
    learning: trace
       
spring:
  #选择配置文件的用途
  profiles:
    active: dev
  #配置数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/train?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
    
mybatis:
  #实体类所在包
  typeAliasesPackage: com.czk.entity
  #mapper.xml所在的位置
  mapperLocations: classpath:mapper/*.xml
  
  